name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_run:
    workflows: [Update PCI Database]
    types: [completed]
  # Manual trigger
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi-beta
      url: https://test.pypi.org/p/torchruntime
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel pytest

      - name: Copy tests
        run: |
          cp -R tests torchruntime/

      - name: Build package
        run: python -m build

      - name: Install and test the package
        run: |
          mkdir /tmp/install-test
          cp dist/*.whl /tmp/install-test
          cd /tmp/install-test
          pip install *.whl

          pip show torchruntime
          python -m torchruntime --help  # test invocation
          pytest --pyargs torchruntime  # run tests

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
